export const transactionHistoryData: TransactionHistory[] = [
	{
		id: 1,
		type: "deposit",
		dateCreated: new Date("2024-09-01"),
		paymentSystem: "Online Banking",
		amount: 1500,
		currency: "USD",
		status: "Pending",
		account: "82763",
	},
	{
		id: 2,
		type: "withdraw",
		dateCreated: new Date("2024-08-30"),
		paymentSystem: "Instant EFT",
		amount: 500,
		currency: "USD",
		status: "Approved",
		account: "82764",
	},
	{
		id: 3,
		type: "transfer",
		dateCreated: new Date("2024-09-02"),
		paymentSystem: "Online Banking",
		amount: 1200,
		currency: "EUR",
		status: "Declined",
		account: "82765",
	},
	{
		id: 4,
		type: "deposit",
		dateCreated: new Date("2024-08-25"),
		paymentSystem: "Instant EFT",
		amount: 2500,
		currency: "USD",
		status: "Approved",
		account: "82766",
	},
	{
		id: 5,
		type: "withdraw",
		dateCreated: new Date("2024-09-01"),
		paymentSystem: "Online Banking",
		amount: 700,
		currency: "GBP",
		status: "Pending",
		account: "82767",
	},
	{
		id: 6,
		type: "transfer",
		dateCreated: new Date("2024-08-28"),
		paymentSystem: "Instant EFT",
		amount: 1300,
		currency: "USD",
		status: "Approved",
		account: "82768",
	},
	{
		id: 7,
		type: "deposit",
		dateCreated: new Date("2024-08-27"),
		paymentSystem: "Online Banking",
		amount: 2200,
		currency: "EUR",
		status: "Declined",
		account: "82769",
	},
	{
		id: 8,
		type: "withdraw",
		dateCreated: new Date("2024-09-02"),
		paymentSystem: "Instant EFT",
		amount: 950,
		currency: "USD",
		status: "Approved",
		account: "82770",
	},
	{
		id: 9,
		type: "transfer",
		dateCreated: new Date("2024-08-30"),
		paymentSystem: "Online Banking",
		amount: 1800,
		currency: "USD",
		status: "Pending",
		account: "82771",
	},
	{
		id: 10,
		type: "deposit",
		dateCreated: new Date("2024-08-29"),
		paymentSystem: "Instant EFT",
		amount: 1750,
		currency: "EUR",
		status: "Approved",
		account: "82772",
	},
	{
		id: 11,
		type: "withdraw",
		dateCreated: new Date("2024-08-26"),
		paymentSystem: "Online Banking",
		amount: 800,
		currency: "GBP",
		status: "Declined",
		account: "82773",
	},
	{
		id: 12,
		type: "transfer",
		dateCreated: new Date("2024-08-24"),
		paymentSystem: "Instant EFT",
		amount: 1500,
		currency: "USD",
		status: "Approved",
		account: "82774",
	},
	{
		id: 13,
		type: "deposit",
		dateCreated: new Date("2024-09-03"),
		paymentSystem: "Online Banking",
		amount: 1300,
		currency: "USD",
		status: "Pending",
		account: "82775",
	},
	{
		id: 14,
		type: "withdraw",
		dateCreated: new Date("2024-08-29"),
		paymentSystem: "Instant EFT",
		amount: 950,
		currency: "GBP",
		status: "Approved",
		account: "82776",
	},
	{
		id: 15,
		type: "transfer",
		dateCreated: new Date("2024-08-25"),
		paymentSystem: "Online Banking",
		amount: 2100,
		currency: "EUR",
		status: "Declined",
		account: "82777",
	},
	{
		id: 16,
		type: "deposit",
		dateCreated: new Date("2024-08-30"),
		paymentSystem: "Instant EFT",
		amount: 1200,
		currency: "USD",
		status: "Pending",
		account: "82778",
	},
	{
		id: 17,
		type: "withdraw",
		dateCreated: new Date("2024-09-04"),
		paymentSystem: "Online Banking",
		amount: 1850,
		currency: "EUR",
		status: "Approved",
		account: "82779",
	},
];
