import { TransactionHistory } from "./columns";

export const transactionHistoryData: TransactionHistory[] = [
	{
		id: 1,
		type: "deposit",
		dateCreated: new Date("2024-09-01"),
		paymentSystem: "Online Banking",
		status: "Pending",
	},
	{
		id: 2,
		type: "withdraw",
		dateCreated: new Date("2024-08-30"),
		paymentSystem: "Instant EFT",
		status: "Approved",
	},
	{
		id: 3,
		type: "transfer",
		dateCreated: new Date("2024-09-02"),
		paymentSystem: "Online Banking",
		status: "Declined",
	},
	{
		id: 4,
		type: "deposit",
		dateCreated: new Date("2024-08-25"),
		paymentSystem: "Instant EFT",
		status: "Approved",
	},
	{
		id: 5,
		type: "withdraw",
		dateCreated: new Date("2024-09-01"),
		paymentSystem: "Online Banking",
		status: "Pending",
	},
	{
		id: 6,
		type: "transfer",
		dateCreated: new Date("2024-08-28"),
		paymentSystem: "Instant EFT",
		status: "Approved",
	},
	{
		id: 7,
		type: "deposit",
		dateCreated: new Date("2024-08-27"),
		paymentSystem: "Online Banking",
		status: "Declined",
	},
	{
		id: 8,
		type: "withdraw",
		dateCreated: new Date("2024-09-02"),
		paymentSystem: "Instant EFT",
		status: "Approved",
	},
	{
		id: 9,
		type: "transfer",
		dateCreated: new Date("2024-08-30"),
		paymentSystem: "Online Banking",
		status: "Pending",
	},
	{
		id: 10,
		type: "deposit",
		dateCreated: new Date("2024-08-29"),
		paymentSystem: "Instant EFT",
		status: "Approved",
	},
	{
		id: 11,
		type: "withdraw",
		dateCreated: new Date("2024-08-26"),
		paymentSystem: "Online Banking",
		status: "Declined",
	},
	{
		id: 12,
		type: "transfer",
		dateCreated: new Date("2024-08-24"),
		paymentSystem: "Instant EFT",
		status: "Approved",
	},
	{
		id: 13,
		type: "deposit",
		dateCreated: new Date("2024-09-03"),
		paymentSystem: "Online Banking",
		status: "Pending",
	},
	{
		id: 14,
		type: "withdraw",
		dateCreated: new Date("2024-08-29"),
		paymentSystem: "Instant EFT",
		status: "Approved",
	},
	{
		id: 15,
		type: "transfer",
		dateCreated: new Date("2024-08-25"),
		paymentSystem: "Online Banking",
		status: "Declined",
	},
	{
		id: 16,
		type: "deposit",
		dateCreated: new Date("2024-08-30"),
		paymentSystem: "Instant EFT",
		status: "Pending",
	},
	{
		id: 17,
		type: "withdraw",
		dateCreated: new Date("2024-09-04"),
		paymentSystem: "Online Banking",
		status: "Approved",
	},
];
