name: CI/CD Deployment

on:
  push:
    branches:
      - master # Jalankan pipeline pada push ke branch "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup SSH Key
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 149.28.150.89 >> ~/.ssh/known_hosts

      # 3. Deploy to VPS
      - name: Deploy to VPS
        run: |
          ssh root@149.28.150.89 'bash -s' < ./update.sh
