name: Deploy to VPS

on:
  push:
    branches:
      - master # Trigger deployment ketika ada push ke branch master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh root@149.28.150.89 'bash -s' < ./update.sh
