name: Deploy to VPS

on:
  push:
    branches:
      - master # Trigger deployment ketika ada push ke branch master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H <vps_ip> >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh root@149.28.150.89 'bash -s' < ./update.sh
